In [7]:
import pandas as pd 
import matplotlib.pyplot as plt

In [8]:
# read the csv file 
data = pd.read_csv('customer_booking.csv', encoding='latin1')
data.head(5)

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,2,Internet,RoundTrip,262,19,7,Sat,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,Internet,RoundTrip,112,20,3,Sat,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,Internet,RoundTrip,243,22,17,Wed,AKLDEL,India,1,1,0,5.52,0
3,1,Internet,RoundTrip,96,31,4,Sat,AKLDEL,New Zealand,0,0,1,5.52,0
4,2,Internet,RoundTrip,68,22,15,Wed,AKLDEL,India,1,0,1,5.52,0

In [9]:

# Assuming you have a DataFrame named 'df' with the relevant data
result = data.groupby('sales_channel').agg({
    'sales_channel': 'count',
    'booking_complete': ['sum', lambda x: (x.sum() / len(x) * 100).round(2)]
}).reset_index()

result.columns = ['sales_channel', 'total_bookings', 'completed_bookings', 'completion_rate']

print(result)

  sales_channel  total_bookings  completed_bookings  completion_rate
0      Internet           44382                6869            15.48
1        Mobile            5618                 609            10.84

In [10]:
# ADD A VISUALISATION HERE

In [11]:
# Assuming you have a DataFrame named 'df' with the relevant data
def categorize_lead_time(lead_time):
    if lead_time <= 30:
        return '0-30 days'
    elif lead_time <= 60:
        return '31-60 days'
    elif lead_time <= 90:
        return '61-90 days'
    else:
        return '90+ days'

# Create the lead_time_category column
data['lead_time_category'] = data['purchase_lead'].apply(categorize_lead_time)

# Perform the groupby and aggregations
result = data.groupby('lead_time_category').agg({
    'lead_time_category': 'count',
    'booking_complete': ['sum', lambda x: (x.sum() / len(x) * 100).round(2)]
}).reset_index()

# Rename the columns
result.columns = ['lead_time_category', 'total_bookings', 'completed_bookings', 'completion_rate']

# Sort the result to match SQL output order
order = ['0-30 days', '31-60 days', '61-90 days', '90+ days']
result = result.set_index('lead_time_category').loc[order].reset_index()

print(result)

  lead_time_category  total_bookings  completed_bookings  completion_rate
0          0-30 days           17139                2819            16.45
1         31-60 days           10668                1616            15.15
2         61-90 days            6347                 863            13.60
3           90+ days           15846                2180            13.76

In [12]:
#Â Add a visualisation here

In [13]:


# Assuming you have a DataFrame named 'df' with the relevant data
def categorize_additional_services(row):
    total_services = row['wants_extra_baggage'] + row['wants_preferred_seat'] + row['wants_in_flight_meals']
    if total_services == 0:
        return 'No additional services'
    elif total_services == 1:
        return '1 additional service'
    elif total_services == 2:
        return '2 additional services'
    else:
        return '3 additional services'

# Create the additional_services column
data['additional_services'] = data.apply(categorize_additional_services, axis=1)

# Perform the groupby and aggregations
result = data.groupby('additional_services').agg({
    'additional_services': 'count',
    'booking_complete': ['sum', lambda x: (x.sum() / len(x) * 100).round(2)]
}).reset_index()

# Rename the columns
result.columns = ['additional_services', 'total_bookings', 'completed_bookings', 'completion_rate']

# Sort the result to match SQL output order
order = ['No additional services', '1 additional service', '2 additional services', '3 additional services']
result = result.set_index('additional_services').loc[order].reset_index()

print(result)

      additional_services  total_bookings  completed_bookings  completion_rate
0  No additional services           10455                1116            10.67
1    1 additional service           18216                2725            14.96
2   2 additional services           12559                2006            15.97
3   3 additional services            8770                1631            18.60

In [14]:
#Â Add a visualisation here

In [16]:



# Assuming you have a DataFrame named 'df' with the relevant data
def categorize_flight_duration(duration):
    if duration < 5:
        return 'Less than 5 hours'
    elif duration < 10:
        return '5-10 hours'
    else:
        return '10+ hours'

# Create the flight_duration_category column
data['flight_duration_category'] = data['flight_duration'].apply(categorize_flight_duration)

# Perform the groupby and aggregations
result = data.groupby('flight_duration_category').agg({
    'flight_duration_category': 'count',
    'booking_complete': ['sum', lambda x: (x.sum() / len(x) * 100).round(2)]
}).reset_index()

# Rename the columns
result.columns = ['flight_duration_category', 'total_bookings', 'completed_bookings', 'completion_rate']

# Define the desired order
order = ['Less than 5 hours', '5-10 hours', '10+ hours']

# Sort the result, including only categories that exist in the data
result = result.set_index('flight_duration_category')
result = result.reindex(index=[category for category in order if category in result.index]).reset_index()

print(result)

  flight_duration_category  total_bookings  completed_bookings  \
0        Less than 5 hours            4656                1234
1               5-10 hours           45344                6244

   completion_rate
0            26.50
1            13.77

In [17]:
# Add a visualisation here

In [19]:
# Assuming you have a DataFrame named 'df' with the relevant data
result = data.groupby('booking_origin').agg({
    'wants_extra_baggage': lambda x: (x.mean() * 100).round(2),
    'wants_preferred_seat': lambda x: (x.mean() * 100).round(2),
    'wants_in_flight_meals': lambda x: (x.mean() * 100).round(2)
}).reset_index()

# Rename the columns
result.columns = ['booking_origin', 'extra_baggage_percentage', 'preferred_seat_percentage', 'in_flight_meals_percentage']

print(result)

#TODO: CONVERT TO A DATAFRAME

           booking_origin  extra_baggage_percentage  \
0               (not set)                     58.33
1             Afghanistan                      0.00
2                 Algeria                      0.00
3               Argentina                     16.67
4               Australia                     70.10
..                    ...                       ...
99   United Arab Emirates                     64.29
100        United Kingdom                     69.36
101         United States                     56.36
102               Vanuatu                    100.00
103               Vietnam                     72.42

     preferred_seat_percentage  in_flight_meals_percentage
0                        22.62                       38.10
1                         0.00                        0.00
2                         0.00                      100.00
3                        16.67                        0.00
4                        34.41                       50.74
..                         ...                         ...
99                       35.71                       59.52
100                      32.37                       39.31
101                      27.85                       31.58
102                     100.00                        0.00
103                      27.32                       37.63

[104 rows x 4 columns]

In [20]:
# ADD A VISUALISATION HERE

In [21]:


# Assuming you have a DataFrame named 'df' with the relevant data
result = data.groupby('flight_day').agg({
    'flight_day': 'count',
    'booking_complete': ['sum', lambda x: (x.sum() / len(x) * 100).round(2)]
}).reset_index()

# Rename the columns
result.columns = ['flight_day', 'total_bookings', 'completed_bookings', 'completion_rate']

# Define the custom order for days
day_order = {'Mon': 1, 'Tue': 2, 'Wed': 3, 'Thu': 4, 'Fri': 5, 'Sat': 6, 'Sun': 7}

# Add a new column for sorting
result['day_order'] = result['flight_day'].map(day_order)

# Sort by the new column and then remove it
result = result.sort_values('day_order').drop('day_order', axis=1)

print(result)

  flight_day  total_bookings  completed_bookings  completion_rate
1        Mon            8102                1204            14.86
5        Tue            7673                1129            14.71
6        Wed            7674                1252            16.31
4        Thu            7424                1122            15.11
0        Fri            6761                 983            14.54
2        Sat            5812                 861            14.81
3        Sun            6554                 927            14.14

In [22]:
# ADD A VISUALISATION HERE

In [23]:


# Assuming you have a DataFrame named 'df' with the relevant data
result = data.groupby('route').agg({
    'num_passengers': ['mean', 'min', 'max']
}).reset_index()

# Flatten the multi-level column names
result.columns = ['route', 'avg_passengers', 'min_passengers', 'max_passengers']

# Round the average to 2 decimal places (optional, to match SQL behavior)
result['avg_passengers'] = result['avg_passengers'].round(2)

print(result)

      route  avg_passengers  min_passengers  max_passengers
0    AKLDEL            1.65               1               4
1    AKLHGH            1.00               1               1
2    AKLHND            2.00               2               2
3    AKLICN            1.41               1               6
4    AKLKIX            1.25               1               2
..      ...             ...             ...             ...
794  TRZWUH            1.08               1               2
795  TRZXIY            1.33               1               2
796  TWUWUH            2.00               2               2
797  TWUXIY            1.57               1               2
798  URTXIY            2.00               2               2

[799 rows x 4 columns]

In [24]:
# ADD A VISUALISATION HERE

In [25]:


# Assuming you have a DataFrame named 'df' with the relevant data
result = data.groupby('trip_type').agg({
    'wants_extra_baggage': lambda x: (x.mean() * 100).round(2),
    'wants_preferred_seat': lambda x: (x.mean() * 100).round(2),
    'wants_in_flight_meals': lambda x: (x.mean() * 100).round(2)
}).reset_index()

# Rename the columns
result.columns = ['trip_type', 'extra_baggage_percentage', 'preferred_seat_percentage', 'in_flight_meals_percentage']

print(result)

    trip_type  extra_baggage_percentage  preferred_seat_percentage  \
0  CircleTrip                     78.45                      29.31
1      OneWay                     71.06                      25.58
2   RoundTrip                     66.82                      29.73

   in_flight_meals_percentage
0                       39.66
1                       34.63
2                       42.78

In [26]:
# ADD A VISUALISATION HERE

In [27]:


# Assuming you have a DataFrame named 'df' with the relevant data
# TODO: CHANGE TO DATAFRAME 

# Step 1: Create service_stats
service_stats = data.groupby(['wants_extra_baggage', 'wants_preferred_seat', 'wants_in_flight_meals']).agg({
    'booking_complete': ['count', 'sum', lambda x: (x.mean() * 100).round(2)]
}).reset_index()

service_stats.columns = ['wants_extra_baggage', 'wants_preferred_seat', 'wants_in_flight_meals', 
                         'total_bookings', 'completed_bookings', 'completion_rate']

# Step 2: Calculate overall stats
overall_stats = pd.DataFrame({
    'avg_completion_rate': [service_stats['completion_rate'].mean()],
    'stddev_completion_rate': [service_stats['completion_rate'].std()]
})

# Step 3: Calculate total additional services and z-score
service_stats['total_additional_services'] = (
    service_stats['wants_extra_baggage'] + 
    service_stats['wants_preferred_seat'] + 
    service_stats['wants_in_flight_meals']
)

service_stats['z_score'] = (
    (service_stats['completion_rate'] - overall_stats['avg_completion_rate'].iloc[0]) / 
    overall_stats['stddev_completion_rate'].iloc[0]
).round(2)

# Step 4: Categorize performance
def categorize_performance(z_score):
    if z_score > 2:
        return 'Significantly Above Average'
    elif z_score > 1:
        return 'Above Average'
    elif z_score < -2:
        return 'Significantly Below Average'
    elif z_score < -1:
        return 'Below Average'
    else:
        return 'Average'

service_stats['performance_category'] = service_stats['z_score'].apply(categorize_performance)

# Step 5: Sort the results
result = service_stats.sort_values('z_score', ascending=False)

print(result)

   wants_extra_baggage  wants_preferred_seat  wants_in_flight_meals  \
7                    1                     1                      1
6                    1                     1                      0
4                    1                     0                      0
3                    0                     1                      1
5                    1                     0                      1
2                    0                     1                      0
1                    0                     0                      1
0                    0                     0                      0

   total_bookings  completed_bookings  completion_rate  \
7            8770                1631            18.60
6            3393                 622            18.33
4           13243                2110            15.93
3            1133                 174            15.36
5            8033                1210            15.06
2            1552                 202            13.02
1            3421                 413            12.07
0           10455                1116            10.67

   total_additional_services  z_score performance_category
7                          3     1.31        Above Average
6                          2     1.22        Above Average
4                          1     0.37              Average
3                          2     0.17              Average
5                          2     0.06              Average
2                          1    -0.66              Average
1                          1    -0.99              Average
0                          0    -1.49        Below Average

In [29]:

# Assuming you have a DataFrame named 'df' with the relevant data
#Â TODO: CONVERT TO DATAFRAME 

# Step 1: Create day_stats
day_stats = data.groupby('flight_day').agg({
    'booking_complete': ['count', 'sum', lambda x: (x.mean() * 100).round(2)],
    'wants_extra_baggage': 'sum',
    'wants_preferred_seat': 'sum',
    'wants_in_flight_meals': 'sum'
}).reset_index()

day_stats.columns = ['flight_day', 'total_bookings', 'completed_bookings', 'completion_rate',
                     'total_extra_baggage', 'total_preferred_seat', 'total_in_flight_meals']

# Step 2: Calculate overall stats
overall_stats = pd.DataFrame({
    'avg_completion_rate': [day_stats['completion_rate'].mean()],
    'stddev_completion_rate': [day_stats['completion_rate'].std()]
})

# Step 3: Calculate z-score
day_stats['z_score'] = (
    (day_stats['completion_rate'] - overall_stats['avg_completion_rate'].iloc[0]) / 
    overall_stats['stddev_completion_rate'].iloc[0]
).round(2)

# Step 4: Categorize performance
def categorize_performance(z_score):
    if z_score > 2:
        return 'Significantly Above Average'
    elif z_score > 1:
        return 'Above Average'
    elif z_score < -2:
        return 'Significantly Below Average'
    elif z_score < -1:
        return 'Below Average'
    else:
        return 'Average'

day_stats['performance_category'] = day_stats['z_score'].apply(categorize_performance)

# Step 5: Calculate additional rates
day_stats['extra_baggage_rate'] = (day_stats['total_extra_baggage'] / day_stats['total_bookings'] * 100).round(2)
day_stats['preferred_seat_rate'] = (day_stats['total_preferred_seat'] / day_stats['total_bookings'] * 100).round(2)
day_stats['in_flight_meals_rate'] = (day_stats['total_in_flight_meals'] / day_stats['total_bookings'] * 100).round(2)

# Step 6: Sort the results
result = day_stats.sort_values('z_score', ascending=False)

print(result)

  flight_day  total_bookings  completed_bookings  completion_rate  \
6        Wed            7674                1252            16.31
4        Thu            7424                1122            15.11
1        Mon            8102                1204            14.86
2        Sat            5812                 861            14.81
5        Tue            7673                1129            14.71
0        Fri            6761                 983            14.54
3        Sun            6554                 927            14.14

   total_extra_baggage  total_preferred_seat  total_in_flight_meals  z_score  \
6                 5161                  2311                   3258     2.03
4                 4988                  2129                   3205     0.27
1                 5372                  2464                   3423    -0.10
2                 3915                  1786                   2515    -0.17
5                 5171                  2181                   3203    -0.32
0                 4515                  1974                   2931    -0.57
3                 4317                  2003                   2822    -1.15

          performance_category  extra_baggage_rate  preferred_seat_rate  \
6  Significantly Above Average               67.25                30.11
4                      Average               67.19                28.68
1                      Average               66.30                30.41
2                      Average               67.36                30.73
5                      Average               67.39                28.42
0                      Average               66.78                29.20
3                Below Average               65.87                30.56

   in_flight_meals_rate
6                 42.46
4                 43.17
1                 42.25
2                 43.27
5                 41.74
0                 43.35
3                 43.06

In [30]:
# ADD A VISUALISATION

In [31]:


# Step 1: Create trip_stats
trip_stats = data.groupby('trip_type').agg({
    'booking_complete': ['count', 'sum', lambda x: (x.mean() * 100).round(2)],
    'wants_extra_baggage': 'sum',
    'wants_preferred_seat': 'sum',
    'wants_in_flight_meals': 'sum'
}).reset_index()

trip_stats.columns = ['trip_type', 'total_bookings', 'completed_bookings', 'completion_rate',
                      'total_extra_baggage', 'total_preferred_seat', 'total_in_flight_meals']

# Step 2: Calculate overall stats
overall_stats = pd.DataFrame({
    'avg_completion_rate': [trip_stats['completion_rate'].mean()],
    'stddev_completion_rate': [trip_stats['completion_rate'].std()]
})

# Step 3: Calculate z-score
trip_stats['z_score'] = (
    (trip_stats['completion_rate'] - overall_stats['avg_completion_rate'].iloc[0]) / 
    overall_stats['stddev_completion_rate'].iloc[0]
).round(2)

# Step 4: Categorize performance
def categorize_performance(z_score):
    if z_score > 2:
        return 'Significantly Above Average'
    elif z_score > 1:
        return 'Above Average'
    elif z_score < -2:
        return 'Significantly Below Average'
    elif z_score < -1:
        return 'Below Average'
    else:
        return 'Average'

trip_stats['performance_category'] = trip_stats['z_score'].apply(categorize_performance)

# Step 5: Calculate additional rates
trip_stats['extra_baggage_rate'] = (trip_stats['total_extra_baggage'] / trip_stats['total_bookings'] * 100).round(2)
trip_stats['preferred_seat_rate'] = (trip_stats['total_preferred_seat'] / trip_stats['total_bookings'] * 100).round(2)
trip_stats['in_flight_meals_rate'] = (trip_stats['total_in_flight_meals'] / trip_stats['total_bookings'] * 100).round(2)

# Step 6: Sort the results
result = trip_stats.sort_values('z_score', ascending=False)

print(result)

    trip_type  total_bookings  completed_bookings  completion_rate  \
2   RoundTrip           49497                7453            15.06
1      OneWay             387                  20             5.17
0  CircleTrip             116                   5             4.31

   total_extra_baggage  total_preferred_seat  total_in_flight_meals  z_score  \
2                33073                 14715                  21177     1.15
1                  275                    99                    134    -0.50
0                   91                    34                     46    -0.65

  performance_category  extra_baggage_rate  preferred_seat_rate  \
2        Above Average               66.82                29.73
1              Average               71.06                25.58
0              Average               78.45                29.31

   in_flight_meals_rate
2                 42.78
1                 34.63
0                 39.66

In [32]:
# ADD A VISUALISATION

In [33]:

# TODO: CONVERT TO DATAFRAME 

# Step 1: Create stay_stats
stay_stats = data.groupby('length_of_stay').agg({
    'booking_complete': ['count', 'sum', lambda x: (x.mean() * 100).round(2)],
    'wants_extra_baggage': 'sum',
    'wants_preferred_seat': 'sum',
    'wants_in_flight_meals': 'sum'
}).reset_index()

stay_stats.columns = ['length_of_stay', 'total_bookings', 'completed_bookings', 'completion_rate',
                      'total_extra_baggage', 'total_preferred_seat', 'total_in_flight_meals']

# Step 2: Calculate overall stats
overall_stats = pd.DataFrame({
    'avg_completion_rate': [stay_stats['completion_rate'].mean()],
    'stddev_completion_rate': [stay_stats['completion_rate'].std()]
})

# Step 3: Calculate z-score
stay_stats['z_score'] = (
    (stay_stats['completion_rate'] - overall_stats['avg_completion_rate'].iloc[0]) / 
    overall_stats['stddev_completion_rate'].iloc[0]
).round(2)

# Step 4: Categorize performance
def categorize_performance(z_score):
    if z_score > 2:
        return 'Significantly Above Average'
    elif z_score > 1:
        return 'Above Average'
    elif z_score < -2:
        return 'Significantly Below Average'
    elif z_score < -1:
        return 'Below Average'
    else:
        return 'Average'

stay_stats['performance_category'] = stay_stats['z_score'].apply(categorize_performance)

# Step 5: Calculate additional rates
stay_stats['extra_baggage_rate'] = (stay_stats['total_extra_baggage'] / stay_stats['total_bookings'] * 100).round(2)
stay_stats['preferred_seat_rate'] = (stay_stats['total_preferred_seat'] / stay_stats['total_bookings'] * 100).round(2)
stay_stats['in_flight_meals_rate'] = (stay_stats['total_in_flight_meals'] / stay_stats['total_bookings'] * 100).round(2)

# Step 6: Sort the results
result = stay_stats.sort_values('z_score', ascending=False)

print(result)

     length_of_stay  total_bookings  completed_bookings  completion_rate  \
334             778               1                   1            100.0
288             337               1                   1            100.0
234             255               1                   1            100.0
230             247               1                   1            100.0
228             244               1                   1            100.0
..              ...             ...                 ...              ...
204             215               1                   0              0.0
205             216               1                   0              0.0
207             218               1                   0              0.0
209             221               2                   0              0.0
0                 0               9                   0              0.0

     total_extra_baggage  total_preferred_seat  total_in_flight_meals  \
334                    0                     0                      0
288                    1                     0                      1
234                    1                     0                      0
230                    1                     1                      1
228                    1                     1                      0
..                   ...                   ...                    ...
204                    1                     1                      1
205                    1                     0                      0
207                    1                     0                      0
209                    2                     0                      1
0                      7                     3                      3

     z_score         performance_category  extra_baggage_rate  \
334     4.01  Significantly Above Average                0.00
288     4.01  Significantly Above Average              100.00
234     4.01  Significantly Above Average              100.00
230     4.01  Significantly Above Average              100.00
228     4.01  Significantly Above Average              100.00
..       ...                          ...                 ...
204    -0.62                      Average              100.00
205    -0.62                      Average              100.00
207    -0.62                      Average              100.00
209    -0.62                      Average              100.00
0      -0.62                      Average               77.78

     preferred_seat_rate  in_flight_meals_rate
334                 0.00                  0.00
288                 0.00                100.00
234                 0.00                  0.00
230               100.00                100.00
228               100.00                  0.00
..                   ...                   ...
204               100.00                100.00
205                 0.00                  0.00
207                 0.00                  0.00
209                 0.00                 50.00
0                  33.33                 33.33

[335 rows x 12 columns]